imports:
  - { resource: ./application.yaml }
  - { resource: ./Orders/application.yaml }

services:
  Shared.EnvironmentArranger:
    class: ../../../../tests/Modules/Shared/infrastructure/persistence/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']
