services:
  Shared.MongoConfig:
    factory:
      class: ../../../../Modules/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.ConnectionManager:
    factory:
      class: ../../../../Modules/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['app', '@Shared.MongoConfig']

  Shared.domain.EventBus:
    class: ../../../../Modules/Shared/infrastructure/eventBus/inMemory/InMemoryAsyncEventBus
    arguments: []
