services:
  App.controllers.health.StatusLivenessController:
    class: ../../controllers/health/StatusLivenessController
    arguments: []

  App.controllers.health.StatusReadinessController:
    class: ../../controllers/health/StatusReadinessController
    arguments: []

  App.controllers.order.OrderPutController:
    class: ../../controllers/order/OrderPutController
    arguments: ['@Modules.Orders.application.OrderCreator']

  App.controllers.orderStatistic.OrderStatisticGetController:
    class: ../../controllers/orderStatistic/OrderStatisticGetController
    arguments: ['@Modules.OrderStatistics.application.OrderStatisticFinder']
