services:
  Modules.Orders.application.OrderCreator:
    class: ../../../../Modules/Orders/application/OrderCreator
    arguments: ['@Modules.Orders.domain.OrderRepository']

  Modules.Orders.domain.OrderRepository:
    class: ../../../../Modules/Orders/infrastructure/persistence/FileOrderRepository
    arguments: ['']
