services:
  Modules.Orders.domain.OrderRepository:
    class: ../../../../Modules/Orders/infrastructure/persistence/MongoOrderRepository
    arguments: ['@Shared.ConnectionManager']

  Modules.Orders.application.OrderCreator:
    class: ../../../../Modules/Orders/application/OrderCreator
    arguments: ['@Modules.Orders.domain.OrderRepository', '@Shared.domain.EventBus']
